name: Generate GitHub Profile Cards

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate stats and languages cards
        run: |
          mkdir -p profile

          curl -o profile/stats.svg \
          "https://github-readme-stats.vercel.app/api?username=saudyahya&show_icons=true&theme=tokyonight"

          curl -o profile/languages.svg \
          "https://github-readme-stats.vercel.app/api/top-langs/?username=saudyahya&layout=compact&theme=tokyonight"

      - name: Commit generated cards
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          git add profile/*.svg
          git commit -m "Update profile cards" || exit 0
          git push
